### ISSUE TITLE
System crashes

### ISSUE THREAD

**Issue by agung-m** [matthiasdiener/cdsm#1]
I had compiled and load the module to kernel successfully,
but when I run a program, it crashes the system, and I need to restart the system manually.
The problem occurs even with a small program with one thread.
The last message found in the kernel log is:
"SPCD: new process app_name (pid..."

Are there any specific prerequisites to run the module?

My system is Centos 7 with kernel version v3.10.0-862, and I compiled CDSM with GCC-4.9.4.

**Comment by matthiasdiener** [comment]
Can you post the output of `uname -a`?

**Comment by agung-m** [comment]
Hi. @matthiasdiener , this is the output of uname -a:

Linux localhost 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matthiasdiener** [comment]
Thanks. In general this version might work (I developed CDSM for kernel 3.2). Can you please post the `dmesg` output related to CDSM?

**Comment by agung-m** [comment]
Sure, I attached the `dmesg` output.
Thank you for your reply. I will check it with the kernel v3.2.

[dmesg_spcd.txt](https://github.com/matthiasdiener/cdsm/files/3287179/dmesg_spcd.txt)

**Comment by agung-m** [comment]
I can confirm that the module runs in kernel v3.2.

**Comment by matthiasdiener** [comment]
Thanks for the confirmation!
